# Generated by Django 2.0.4 on 2018-04-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='description',
            field=models.TextField(),
        ),
    ]
